#!/bin/sh

mailman3_cfg="/etc/mailman3/mailman.cfg"

port="$(sed -ne 's|^port:\s*\(\S\+\)|\1|p' $mailman3_cfg)"
admin_user="$(sed -ne 's|^admin_user:\s*\(\S\+\)|\1|p' $mailman3_cfg)"
admin_pass="$(sed -ne 's|^admin_pass:\s*\(\S\+\)|\1|p' $mailman3_cfg)"

curl -s --user "$admin_user:$admin_pass" http://localhost:$port/3.1/system/versions
