#!/bin/bash

# install postfix
debconf-set-selections <<< "postfix postfix/mailname string localhost" 2>&1
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'" 2>&1
hostname localhost
apt-get install -y postfix 2>&1

# restart mailman3 after postfix is available
systemctl restart mailman3

mailman3_cfg="/etc/mailman3/mailman.cfg"

port="$(sed -ne 's|^port:\s*\(\S\+\)|\1|p' $mailman3_cfg)"
admin_user="$(sed -ne 's|^admin_user:\s*\(\S\+\)|\1|p' $mailman3_cfg)"
admin_pass="$(sed -ne 's|^admin_pass:\s*\(\S\+\)|\1|p' $mailman3_cfg)"

curl -s --user "$admin_user:$admin_pass" http://localhost:$port/3.1/system/versions
