#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm

init_service_failed () {
    db_input high mailman3/init_service_failed || true
    db_go
}

case "$1" in
    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

# database removal has to happen after service is stopped
dbc_go mailman3 "$@"

db_stop
exit 0
